/**
 * The shared look of the demo examples.
 *
 * The examples used to ship one stylesheet each — query, mutation, the table
 * demos, the full demo — and the `craft/` and `primitives/` variants of the
 * same example carried two copies of it. They share this sheet instead: a card,
 * the text inside it, controls, a data table, pagination and form fields.
 * What only one example has (the pixel grid, the task board) stays in that
 * example's own sheet, next to it.
 *
 * Variants are state axes, set as `data-*` attributes on the element:
 * `data-exampleCard` (the dark card of the mutation demos), `data-exampleButton`
 * (primary, danger, ghost, subtle) and `data-exampleText` (muted, error, success).
 */
import {
  alignContent,
  at,
  alignItems,
  alignSelf,
  animate,
  bg,
  blockSize,
  borderBlockEndColor,
  borderBlockEndStyle,
  borderBlockEndWidth,
  borderCollapse,
  borderColor,
  borderInlineStartColor,
  borderInlineStartStyle,
  borderInlineStartWidth,
  borderStyle,
  borderTopColor,
  borderWidth,
  color,
  craftStyles,
  cssVars,
  cursor,
  defineBreakpoints,
  definePalette,
  defineStateAxis,
  display,
  easing,
  flex,
  gridTemplateColumns,
  flexDirection,
  flexWrap,
  font,
  fontFamily,
  fontSize,
  fontWeight,
  gap,
  inlineSize,
  interaction,
  justifyContent,
  keyframes,
  kind,
  letterSpacing,
  lineHeight,
  lineWidth,
  listStyleType,
  marginBlockStart,
  marginInline,
  math,
  maxInlineSize,
  minBlockSize,
  minWidth,
  monospaceStack,
  num,
  opacity,
  p,
  paddingInlineStart,
  provides,
  px,
  py,
  radii,
  radius,
  rotate,
  scrollPort,
  set,
  shadow,
  space,
  tracks,
  text,
  textAlign,
  textDecorationLine,
  unit,
  when,
  whiteSpace,
} from '@craft-ts/style';

const ex = definePalette('example', {
  surface: {
    page: { light: '#f5f7fa', dark: '#f5f7fa' },
    card: { light: '#ffffff', dark: '#ffffff' },
    sunken: { light: '#f8fafc', dark: '#f8fafc' },
    code: { light: '#0f172a', dark: '#0f172a' },
    info: { light: '#eff6ff', dark: '#eff6ff' },
    primary: { light: '#2563eb', dark: '#2563eb' },
    primaryHover: { light: '#1d4ed8', dark: '#1d4ed8' },
    danger: { light: '#dc2626', dark: '#dc2626' },
    dangerHover: { light: '#b91c1c', dark: '#b91c1c' },
    subtle: { light: '#ebf8ff', dark: '#ebf8ff' },
    subtleHover: { light: '#bee3f8', dark: '#bee3f8' },
    badge: { light: '#e0e7ff', dark: '#e0e7ff' },
    error: { light: '#fef2f2', dark: '#fef2f2' },
    success: { light: '#f0fdf4', dark: '#f0fdf4' },
    dark: { light: '#232323', dark: '#232323' },
    hero: { light: '#0f172a', dark: '#0f172a' },
    teal: { light: '#f0fdfa', dark: '#f0fdfa' },
    warning: { light: '#fff7ed', dark: '#fff7ed' },
    darkControl: { light: '#444444', dark: '#444444' },
    darkControlHover: { light: '#2a2a2a', dark: '#2a2a2a' },
    darkCode: { light: '#181818', dark: '#181818' },
    transparent: { light: 'transparent', dark: 'transparent' },
  },
  text: {
    strong: { light: '#1a202c', dark: '#1a202c' },
    body: { light: '#334155', dark: '#334155' },
    muted: { light: '#4a5568', dark: '#4a5568' },
    code: { light: '#dbeafe', dark: '#dbeafe' },
    onPrimary: { light: '#ffffff', dark: '#ffffff' },
    subtle: { light: '#2b6cb0', dark: '#2b6cb0' },
    badge: { light: '#3730a3', dark: '#3730a3' },
    error: { light: '#b91c1c', dark: '#b91c1c' },
    success: { light: '#166534', dark: '#166534' },
    onDark: { light: '#eaeaea', dark: '#eaeaea' },
    onDarkMuted: { light: '#bdbdbd', dark: '#bdbdbd' },
    darkCode: { light: '#d6d6d6', dark: '#d6d6d6' },
    onHero: { light: '#f8fafc', dark: '#f8fafc' },
    warning: { light: '#9a3412', dark: '#9a3412' },
    danger: { light: '#991b1b', dark: '#991b1b' },
    term: { light: '#374151', dark: '#374151' },
    definition: { light: '#6b7280', dark: '#6b7280' },
    done: { light: '#6b7280', dark: '#6b7280' },
  },
  border: {
    card: { light: '#dce4ef', dark: '#dce4ef' },
    subtle: { light: '#edf2f7', dark: '#edf2f7' },
    control: { light: '#cbd5e1', dark: '#cbd5e1' },
    focus: { light: '#93c5fd', dark: '#93c5fd' },
    code: { light: '#1e293b', dark: '#1e293b' },
    primary: { light: '#2563eb', dark: '#2563eb' },
    error: { light: '#fecaca', dark: '#fecaca' },
    dark: { light: '#444444', dark: '#444444' },
    teal: { light: '#99f6e4', dark: '#99f6e4' },
    warning: { light: '#f97316', dark: '#f97316' },
    danger: { light: '#fca5a5', dark: '#fca5a5' },
    success: { light: '#bbf7d0', dark: '#bbf7d0' },
  },
  effect: {
    shadow: { light: '#0f172a14', dark: '#0f172a14' },
    soft: { light: '#0000000d', dark: '#0000000d' },
  },
});

/** The dark card of the mutation demos. Drives `data-exampleCard`. */
export const cardTone = defineStateAxis('exampleCard', ['dark']);

/** A button's role. The default is a neutral outline. */
export const buttonTone = defineStateAxis('exampleButton', [
  'primary',
  'danger',
  'ghost',
  'subtle',
]);

/** How serious an alert is. Drives `data-exampleAlert`. */
export const alertTone = defineStateAxis('exampleAlert', [
  'warning',
  'danger',
  'success',
]);

/** A field that takes the whole row. Drives `data-exampleField`. */
export const fieldWidth = defineStateAxis('exampleField', ['wide']);

/** A line of text with a meaning. Drives `data-exampleText`. */
export const textTone = defineStateAxis('exampleText', [
  'muted',
  'error',
  'success',
  'done',
]);

const themed = { inherits: true };

/**
 * What the card lets its children read. The light values are the defaults;
 * the dark card sets the other side, and no child mentions the tone.
 */
const tone = cssVars('example', {
  ink: kind.color(ex.text.strong, themed),
  muted: kind.color(ex.text.muted, themed),
  control: kind.color(ex.text.body, themed),
  controlSurface: kind.color(ex.surface.card, themed),
  controlHover: kind.color(ex.surface.info, themed),
  controlBorder: kind.color(ex.border.control, themed),
  codeInk: kind.color(ex.text.code, themed),
  codeSurface: kind.color(ex.surface.code, themed),
});

const hairline = (tint: Parameters<typeof borderColor>[0]) => [
  borderWidth(lineWidth.hairline),
  borderStyle.solid,
  borderColor(tint),
];

const bp = defineBreakpoints({ wide: at.minInlineSize(unit.rem(48)) });

const spin = keyframes('exampleSpin', { to: [rotate(unit.deg(360))] });

export const example = craftStyles('example', {
  /** A full-width area, for the dashboards (table, sidebar). */
  page: [
    display.grid,
    alignContent.start,
    gap(space(5)),
    minBlockSize(unit.pct(100)),
    p(space(6)),
    color(ex.text.strong),
    bg(ex.surface.page),
  ],
  /** The card an example sits in. */
  card: [
    display.grid,
    gap(space(4)),
    inlineSize(math.min(unit.pct(100), unit.rem(46))),
    marginInline.auto,
    marginBlockStart(space(8)),
    p(math.clamp(unit.rem(1.25), unit.vw(4), unit.rem(2))),
    ...hairline(ex.border.card),
    radius(unit.rem(1.25)),
    color(tone.ink),
    bg(ex.surface.card),
    shadow({ y: unit.rem(1.5), blur: unit.rem(3), color: ex.effect.shadow }),
    when(cardTone.dark, [
      set(tone.ink, ex.text.onDark),
      set(tone.muted, ex.text.onDarkMuted),
      set(tone.control, ex.text.onDark),
      set(tone.controlSurface, ex.surface.darkControl),
      set(tone.controlHover, ex.surface.darkControlHover),
      set(tone.controlBorder, ex.border.dark),
      set(tone.codeInk, ex.text.darkCode),
      set(tone.codeSurface, ex.surface.darkCode),
      inlineSize(math.min(unit.pct(100), unit.px(420))),
      borderStyle.none,
      radius(unit.px(14)),
      bg(ex.surface.dark),
    ]),
  ],
  /** A wide panel with no card chrome of its own, for the table demos. */
  panel: [
    inlineSize(unit.pct(100)),
    maxInlineSize(unit.px(900)),
    marginInline.auto,
    p(space(6)),
    radius(radii.xl),
    bg(ex.surface.card),
    shadow({ y: unit.px(2), blur: unit.px(4), color: ex.effect.soft }),
  ],
  title: [
    display.flex,
    alignItems.center,
    gap(space(2)),
    fontSize(unit.px(24)),
    fontWeight(num(600)),
    lineHeight(num(1.25)),
  ],
  subtitle: [font(text.lg), fontWeight(num(600))],
  text: [
    lineHeight(num(1.5)),
    when(textTone.muted, [color(tone.muted)]),
    when(textTone.error, [color(ex.text.error)]),
    when(textTone.success, [color(ex.text.success)]),
  ],
  row: [display.flex, flexWrap.wrap, alignItems.center, gap(space(2))],
  /** A row of controls in a tinted band. */
  toolbar: [
    display.flex,
    flexWrap.wrap,
    alignItems.center,
    gap(space(3)),
    py(space(4)),
    px(space(5)),
    ...hairline(ex.border.control),
    radius(radii.xl),
    bg(ex.surface.sunken),
  ],
  stack: [display.grid, gap(space(3))],
  result: [
    p(math.clamp(unit.rem(1), unit.vw(3), unit.rem(1.5))),
    ...hairline(ex.border.subtle),
    radius(unit.rem(0.9)),
    font(text.base),
    fontWeight(num(700)),
    bg(ex.surface.sunken),
  ],
  code: [
    marginBlockStart(space(4)),
    py(space(4)),
    px(space(4)),
    provides(scrollPort.inline),
    ...hairline(ex.border.code),
    radius(radii.xl),
    fontFamily(monospaceStack),
    font(text.sm),
    fontWeight(num(400)),
    whiteSpace.preWrap,
    color(tone.codeInk),
    bg(tone.codeSurface),
  ],
  note: [
    py(space(3)),
    px(space(4)),
    borderInlineStartWidth(unit.px(3)),
    borderInlineStartStyle.solid,
    borderInlineStartColor(ex.border.focus),
    radius(radii.lg),
    font(text.sm),
    color(ex.text.muted),
    bg(ex.surface.sunken),
  ],
  actions: [
    display.flex,
    flexWrap.wrap,
    alignItems.center,
    justifyContent.flexEnd,
    gap(space(3)),
  ],
  button: [
    display.inlineFlex,
    alignItems.center,
    justifyContent.center,
    minBlockSize(unit.rem(2.5)),
    py(space(2)),
    px(space(4)),
    ...hairline(tone.controlBorder),
    radius(radii.lg),
    font(text.sm),
    fontWeight(num(700)),
    cursor.pointer,
    color(tone.control),
    bg(tone.controlSurface),
    when(interaction.hover, [bg(tone.controlHover)]),
    when(buttonTone.primary, [
      borderColor(ex.border.primary),
      color(ex.text.onPrimary),
      bg(ex.surface.primary),
      when(interaction.hover, [bg(ex.surface.primaryHover)]),
    ]),
    when(buttonTone.danger, [
      borderColor(ex.surface.danger),
      color(ex.text.onPrimary),
      bg(ex.surface.danger),
      when(interaction.hover, [bg(ex.surface.dangerHover)]),
    ]),
    when(buttonTone.subtle, [
      borderStyle.none,
      fontWeight(num(500)),
      color(ex.text.subtle),
      bg(ex.surface.subtle),
      when(interaction.hover, [bg(ex.surface.subtleHover)]),
    ]),
    when(buttonTone.ghost, [
      minBlockSize(unit.px(0)),
      p(space(1)),
      borderStyle.none,
      bg(ex.surface.transparent),
    ]),
    when(interaction.disabled, [cursor.notAllowed, opacity(num(0.5))]),
  ],
  label: [font(text.sm), fontWeight(num(500)), color(tone.muted)],
  input: [
    inlineSize(unit.pct(100)),
    maxInlineSize(unit.px(300)),
    minWidth(space(0)),
    py(space(2)),
    px(space(3)),
    ...hairline(tone.controlBorder),
    radius(radii.lg),
    color(tone.ink),
    bg(tone.controlSurface),
    when(interaction.focus, [borderColor(ex.border.primary)]),
    when(fieldWidth.wide, [maxInlineSize.none]),
  ],
  select: [
    py(space(2)),
    px(space(4)),
    ...hairline(ex.border.control),
    radius(radii.md),
    fontWeight(num(500)),
    cursor.pointer,
    color(ex.text.muted),
    bg(ex.surface.card),
    when(interaction.focus, [borderColor(ex.border.primary)]),
  ],
  table: [inlineSize(unit.pct(100)), borderCollapse.collapse],
  tableRow: [when(interaction.hover, [bg(ex.surface.sunken)])],
  emptyCell: [p(space(8)), textAlign.center],
  th: [
    p(space(4)),
    textAlign.start,
    borderBlockEndWidth(lineWidth.hairline),
    borderBlockEndStyle.solid,
    borderBlockEndColor(ex.border.subtle),
    fontWeight(num(600)),
    color(ex.text.muted),
    bg(ex.surface.sunken),
  ],
  td: [
    p(space(4)),
    textAlign.start,
    borderBlockEndWidth(lineWidth.hairline),
    borderBlockEndStyle.solid,
    borderBlockEndColor(ex.border.subtle),
  ],
  pagination: [
    display.flex,
    flexWrap.wrap,
    justifyContent.flexEnd,
    gap(space(2)),
    marginBlockStart(space(5)),
  ],
  currentPage: [alignSelf.center, fontWeight(num(600)), color(ex.text.muted)],
  badge: [
    display.inlineFlex,
    alignItems.center,
    gap(space(1)),
    py(space(1)),
    px(space(2)),
    radius(radii.full),
    font(text.xs),
    fontWeight(num(600)),
    color(ex.text.badge),
    bg(ex.surface.badge),
  ],
  list: [display.grid, gap(space(2)), p(space(0)), listStyleType.none],
  item: [
    display.flex,
    alignItems.center,
    justifyContent.spaceBetween,
    gap(space(3)),
    py(space(3)),
    px(space(4)),
    ...hairline(ex.border.subtle),
    radius(radii.lg),
    bg(ex.surface.card),
  ],
  /** The label of a list item; `data-exampleText="done"` strikes it through. */
  itemTitle: [
    flex(num(1)),
    when(textTone.done, [color(ex.text.done), textDecorationLine.lineThrough]),
  ],
  error: [
    py(space(3)),
    px(space(4)),
    ...hairline(ex.border.error),
    radius(radii.lg),
    color(ex.text.error),
    bg(ex.surface.error),
  ],
  hint: [font(text.xs), color(ex.text.muted)],
  spinner: [
    display.inlineBlock,
    inlineSize(space(4)),
    blockSize(space(4)),
    borderWidth(lineWidth.thick),
    borderStyle.solid,
    borderColor(ex.border.control),
    borderTopColor(ex.border.primary),
    radius(radii.full),
    animate(spin, {
      duration: unit.ms(800),
      easing: easing.linear,
      iterations: 'infinite',
    }),
  ],
  sidebar: [inlineSize(unit.px(300)), flex(num(0))],
  /** An error screen or a warning block. */
  alert: [
    display.grid,
    gap(space(3)),
    p(space(8)),
    ...hairline(ex.border.card),
    radius(radii.lg),
    bg(ex.surface.sunken),
    when(alertTone.warning, [
      borderColor(ex.border.warning),
      color(ex.text.warning),
      bg(ex.surface.warning),
    ]),
    when(alertTone.danger, [
      borderColor(ex.border.danger),
      color(ex.text.danger),
      bg(ex.surface.error),
    ]),
    when(alertTone.success, [
      borderColor(ex.border.success),
      color(ex.text.success),
      bg(ex.surface.success),
    ]),
  ],
  hero: [
    display.grid,
    gap(space(2)),
    p(space(6)),
    radius(unit.px(24)),
    color(ex.text.onHero),
    bg(ex.surface.hero),
  ],
  split: [
    display.grid,
    gap(space(5)),
    gridTemplateColumns(tracks.list(tracks.minmax(space(0), tracks.fr(1)))),
    when(bp.wide, [
      gridTemplateColumns(
        tracks.list(
          tracks.minmax(space(0), tracks.fr(1.2)),
          tracks.minmax(space(0), tracks.fr(1)),
        ),
      ),
    ]),
  ],
  tealCard: [
    display.grid,
    gap(space(3)),
    p(space(6)),
    ...hairline(ex.border.teal),
    radius(unit.px(20)),
    bg(ex.surface.teal),
  ],
  centered: [
    display.flex,
    flexDirection.column,
    alignItems.center,
    gap(space(4)),
    p(space(8)),
  ],
  bigValue: [fontSize(unit.rem(3)), fontWeight(num(700))],
  box: [
    display.grid,
    gap(space(1)),
    p(space(3)),
    ...hairline(ex.border.control),
    radius(radii.lg),
    bg(ex.surface.sunken),
  ],
  tiles: [
    display.grid,
    gridTemplateColumns(tracks.autoFit(unit.rem(10))),
    gap(space(3)),
  ],
  definitions: [
    display.grid,
    gridTemplateColumns(tracks.list('auto', tracks.fr(1))),
    gap(space(2)),
  ],
  term: [fontWeight(num(600)), color(ex.text.term)],
  definition: [color(ex.text.definition)],
  columns: [display.flex, flexDirection.column, gap(space(6))],
  fieldset: [display.grid, gap(space(2)), paddingInlineStart(space(0))],
  mono: [fontFamily(monospaceStack), font(text.sm), letterSpacing(unit.em(0))],
});
