/**
 * The demo's foundation and its shell: the font, the document, the banner, the
 * examples menu and the frame every example renders in.
 *
 * The examples bring their own sheets; what is here is what every page shares.
 * The reset and the good defaults (focus ring, reduced motion) come from
 * craft-ts itself — see `craftStyle()` in `vite.config.ts`.
 */
import { craftAiLauncherPosition } from '@craft-ts/component/style';
import {
  alignContent,
  alignItems,
  bg,
  borderBlockEndColor,
  borderBlockEndStyle,
  borderBlockEndWidth,
  borderColor,
  borderStyle,
  borderWidth,
  bottom,
  color,
  craftGlobalStyles,
  craftStyles,
  cursor,
  defineFont,
  definePalette,
  display,
  flex,
  flexDirection,
  flexShrink,
  flexWrap,
  font,
  fontFamily,
  fontWeight,
  gap,
  googleFont,
  gridTemplateColumns,
  interaction,
  justifyContent,
  left,
  lineHeight,
  lineWidth,
  margin,
  marginBlockStart,
  blockSize,
  num,
  p,
  position,
  provides,
  px,
  py,
  radii,
  radius,
  right,
  scrollPort,
  set,
  shadow,
  space,
  text,
  textDecorationLine,
  textUnderlineOffset,
  top,
  tracks,
  unit,
  when,
  zIndex,
  int,
} from '@craft-ts/style';

const chivo = defineFont('demoBody', {
  family: 'Chivo',
  source: googleFont({ weights: [400, 600, 700] }),
  display: 'swap',
  fallback: 'sans-serif',
});

const demo = definePalette('demoShell', {
  surface: {
    page: { light: '#fafafa', dark: '#fafafa' },
    raised: { light: '#ffffff', dark: '#ffffff' },
    banner: { light: '#eff6ff', dark: '#eff6ff' },
    hover: { light: '#f3f4f6', dark: '#f3f4f6' },
    action: { light: '#374151', dark: '#374151' },
  },
  text: {
    strong: { light: '#111827', dark: '#111827' },
    body: { light: '#374151', dark: '#374151' },
    muted: { light: '#4b5563', dark: '#4b5563' },
    hint: { light: '#475569', dark: '#475569' },
    banner: { light: '#1e3a8a', dark: '#1e3a8a' },
    link: { light: '#1d4ed8', dark: '#1d4ed8' },
    onAction: { light: '#ffffff', dark: '#ffffff' },
  },
  border: {
    banner: { light: '#bfdbfe', dark: '#bfdbfe' },
    subtle: { light: '#e5e7eb', dark: '#e5e7eb' },
    control: { light: '#d1d5db', dark: '#d1d5db' },
  },
  effect: {
    shadow: { light: '#1118271c', dark: '#1118271c' },
  },
});

craftGlobalStyles('demo', {
  // The AI launcher is a fixed overlay on <body>; this keeps it under the
  // demo's own floating Clear Cache button instead of behind it.
  root: [
    set(craftAiLauncherPosition.right, space(8)),
    set(craftAiLauncherPosition.bottom, space(8)),
  ],
  elements: {
    body: [fontFamily(chivo), color(demo.text.body)],
  },
});

export const demoShell = craftStyles('demoShell', {
  root: [
    display.flex,
    flexDirection.column,
    blockSize(unit.vh(100)),
    bg(demo.surface.page),
  ],
  banner: [
    display.grid,
    flexShrink(num(0)),
    gap(space(1)),
    py(space(3)),
    px(space(5)),
    borderBlockEndWidth(lineWidth.hairline),
    borderBlockEndStyle.solid,
    borderBlockEndColor(demo.border.banner),
    font(text.sm),
    color(demo.text.banner),
    bg(demo.surface.banner),
  ],
  bannerMain: [display.flex, flexWrap.wrap, alignItems.center, gap(space(2))],
  bannerStrong: [fontWeight(num(700))],
  bannerLink: [
    fontWeight(num(700)),
    textDecorationLine.underline,
    textUnderlineOffset(unit.px(2)),
    color(demo.text.link),
    when(interaction.hover, [color(demo.text.banner)]),
  ],
  bannerHint: [font(text.xs), color(demo.text.hint)],
  bannerHintStrong: [color(demo.text.strong)],
  nav: [
    position.relative,
    zIndex(int(2)),
    display.flex,
    alignItems.center,
    justifyContent.spaceBetween,
    gap(space(4)),
    py(space(3)),
    px(space(5)),
    borderBlockEndWidth(lineWidth.hairline),
    borderBlockEndStyle.solid,
    borderBlockEndColor(demo.border.subtle),
    bg(demo.surface.raised),
  ],
  navToggle: [
    py(space(2)),
    px(space(3)),
    borderWidth(lineWidth.hairline),
    borderStyle.solid,
    borderColor(demo.border.control),
    radius(radii.md),
    fontWeight(num(600)),
    cursor.pointer,
    color(demo.text.body),
    bg(demo.surface.raised),
    when(interaction.hover, [bg(demo.surface.hover)]),
  ],
  navPanel: [
    position.absolute,
    top(unit.pct(100)),
    left(space(5)),
    right(space(5)),
    display.grid,
    gridTemplateColumns(tracks.autoFit(unit.rem(12))),
    gap(space(5)),
    marginBlockStart(space(2)),
    p(space(4)),
    borderWidth(lineWidth.hairline),
    borderStyle.solid,
    borderColor(demo.border.subtle),
    radius(radii.xl),
    bg(demo.surface.raised),
    shadow({ y: unit.px(12), blur: unit.px(30), color: demo.effect.shadow }),
  ],
  navGroup: [display.grid, alignContent.start, gap(space(2))],
  navGroupTitle: [font(text.sm), color(demo.text.strong)],
  navLinks: [display.grid, gap(space(1))],
  navLink: [
    py(space(1)),
    px(space(2)),
    radius(radii.sm),
    font(text.sm),
    textDecorationLine.none,
    color(demo.text.muted),
    when(interaction.hover, [color(demo.text.strong), bg(demo.surface.hover)]),
  ],
  content: [
    flex(num(1)),
    provides(scrollPort.block),
    margin(space(6)),
    p(space(8)),
    radius(radii.lg),
    bg(demo.surface.raised),
  ],
  clearCache: [
    position.fixed,
    bottom(unit.rem(5.5)),
    right(space(8)),
    py(space(4)),
    px(space(6)),
    borderStyle.none,
    radius(radii.full),
    cursor.pointer,
    lineHeight(num(1)),
    color(demo.text.onAction),
    bg(demo.surface.action),
  ],
});
